name: Build Linux Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: |
        flutter pub get
        sudo apt-get update
        sudo apt-get install -y build-essential libgtk-3-dev libglib2.0-dev

    - name: Build Flutter Linux app
      run: flutter build linux

    - name: Package as .deb
      run: |
        mkdir -p package/DEBIAN
        echo "Package: pilipalax" >> package/DEBIAN/control
        echo "Version: 1.0.22" >> package/DEBIAN/control
        echo "Section: utils" >> package/DEBIAN/control
        echo "Priority: optional" >> package/DEBIAN/control
        echo "Architecture: amd64" >> package/DEBIAN/control
        echo "Depends: flutter" >> package/DEBIAN/control
        echo "Description: A new Flutter project." >> package/DEBIAN/control

        cp -r build/linux/x64/release/bundle/* package/
        dpkg-deb --build package

    - name: Create AppImage
      run: |
        # Install necessary dependencies for AppImage
        sudo apt-get install -y appimagetool

        # Create the AppImage
        appimagetool build/linux/x64/release/bundle pilipalax.AppImage

    - name: Upload to Releases
      uses: softprops/action-gh-release@v1
      with:
        files: |
          package.deb
          pilipalax.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
