linux:
  name: Build CI (Linux)
  needs: update_version
  runs-on: ubuntu-latest

  steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg appimagetool

  - name: 更新版本号
      id: version
      run: |
        # 更新pubspec.yaml文件中的版本号
        sed -i "s/version: .*/version: ${{ needs.update_version.outputs.new_version }}/g" pubspec.yaml

  - name: flutter build linux
      run: flutter build linux --release

  - name: Create DEB package
      run: |
        mkdir -p package/DEBIAN
        echo "Package: my-flutter-app" > package/DEBIAN/control
        echo "Version: ${{ needs.update_version.outputs.new_version }}" >> package/DEBIAN/control
        echo "Architecture: amd64" >> package/DEBIAN/control
        echo "Maintainer: Your Name <youremail@example.com>" >> package/DEBIAN/control
        echo "Description: My Flutter Linux application" >> package/DEBIAN/control
        cp -r build/linux/x64/release/bundle/* package/
        dpkg-deb --build package my-flutter-app_${{ needs.update_version.outputs.new_version }}_amd64.deb

  - name: Create AppImage
      run: |
        appimagetool --input build/linux/x64/release/bundle/ --output build/my-flutter-app-${{ needs.update_version.outputs.new_version }}.AppImage

  - name: 上传
      uses: actions/upload-artifact@v3
      with:
        name: Linux-Builds
        path: |
          my-flutter-app_${{ needs.update_version.outputs.new_version }}_amd64.deb
          build/my-flutter-app-${{ needs.update_version.outputs.new_version }}.AppImage

release:
  - name: Release
  - runs-on: ubuntu-latest
  - needs: linux
  - if: needs.linux.outputs.version_code != ''

steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Upload to GitHub Releases
    uses: ncipollo/release-action@v1
    with:
      tag: ${{ needs.update_version.outputs.new_version }}
      name: Release ${{ needs.update_version.outputs.new_version }}
      files: |
        my-flutter-app_${{ needs.update_version.outputs.new_version }}_amd64.deb
        build/my-flutter-app-${{ needs.update_version.outputs.new_version }}.AppImage
      token: ${{ secrets.GIT_TOKEN }}


